<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>52f49abd-fef1-45b2-b355-a3dff13740c7</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_bike_light</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-bike-light</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-bike-light') and equals(@name,'add-to-cart-sauce-labs-bike-light') and equals(@class,'btn btn_primary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory</value>
        <webElementGuid>cf9455ba-3071-41ad-b1e7-908153e8f3e2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bike-light</value>
        <webElementGuid>4166fb73-22bf-4dd5-bb67-b1e194c8e226</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-bike-light</value>
        <webElementGuid>fb588761-eafc-498a-90af-547b19feadb4</webElementGuid>
    </webElementProperties>
</WebElementEntity>