<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1702aea7-1878-48ac-94dc-1d691d98c5c2</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[7]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiInputBase-root\\ MuiOutlinedInput-root\\ MuiInputBase-colorPrimary\\ MuiInputBase-fullWidth\\ MuiInputBase-formControl\\ MuiInputBase-sizeSmall\\ MuiInputBase-adornedEnd\\ MuiAutocomplete-inputRoot\\ css-cxvqo3"] [class="MuiButtonBase-root\\ MuiIconButton-root\\ MuiIconButton-sizeMedium\\ MuiAutocomplete-popupIndicator\\ css-13hgt6x"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid="traffic-filter"] &gt;&gt; internal:label="Open"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>dced2919-fce0-468a-96b2-671df63b5cd0</webElementGuid>
    </webElementProperties>
</WebElementEntity>