<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>241dc192-3a3b-4138-b405-eb9715af15c3</elementGuidId>
    <imagePath></imagePath>
    <name>link_item_1_title_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#item_1_title_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'item_1_title_link') and equals(@text,'Sauce Labs Bolt T-Shirt')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="item-1-title-link"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>item_1_title_link</value>
        <webElementGuid>69a2d286-4b83-4f32-b832-ddf778f50327</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sauce Labs Bolt T-Shirt</value>
        <webElementGuid>69a2d286-4b83-4f32-b832-ddf778f50327</webElementGuid>
    </webElementProperties>
</WebElementEntity>