<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fdcc3a7c-4a8f-4d77-9d8f-ca400047795a</elementGuidId>
    <imagePath></imagePath>
    <name>input_first_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#first-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'first-name') and equals(@name,'firstName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>d7a0a944-24bc-4cce-9e78-179a09b89ab3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>first-name</value>
        <webElementGuid>e495b419-65c3-469c-a968-9f7f1b2b653f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>firstName</value>
        <webElementGuid>2d1284d9-9c53-48e1-aa8e-fcf0f956ac66</webElementGuid>
    </webElementProperties>
</WebElementEntity>