<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b1242203-7667-4ec5-b808-1e538ef2dd63</elementGuidId>
    <imagePath></imagePath>
    <name>input_last_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#last-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'last-name') and equals(@name,'lastName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>c9028305-7eaa-4ac7-b4e7-93fed3aa0f94</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>last-name</value>
        <webElementGuid>c96560af-0178-46f8-be4a-24b4cc95c5b1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>lastName</value>
        <webElementGuid>3070067c-6699-4d1f-8432-b883a8c8e190</webElementGuid>
    </webElementProperties>
</WebElementEntity>