<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e34e980f-797b-426d-acf2-5358702fb388</elementGuidId>
    <imagePath></imagePath>
    <name>input_postal_code</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#postal-code</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'postal-code') and equals(@name,'postalCode') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>210fa3ba-4f58-46d1-8079-933df976549a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>postal-code</value>
        <webElementGuid>0912ffb1-b7e3-49b6-8239-144b22c04f32</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>postalCode</value>
        <webElementGuid>fad2372c-1e88-4f5d-95a8-9c819120ab37</webElementGuid>
    </webElementProperties>
</WebElementEntity>