<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d1036657-cda2-4811-b692-1f822673bc7a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_menu_truetest</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[2]/nav[1]/ul[1]/li[6]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-item"]:nth-child(6) &gt; [class="nav-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'menu-truetest') and equals(@text,'TrueTest')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid="menu-truetest"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>menu-truetest</value>
        <webElementGuid>72bcdbbe-3534-402b-8339-a704caf81227</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TrueTest</value>
        <webElementGuid>72bcdbbe-3534-402b-8339-a704caf81227</webElementGuid>
    </webElementProperties>
</WebElementEntity>