<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fd5c1d93-4c0b-4067-aec8-ff57341900af</elementGuidId>
    <imagePath></imagePath>
    <name>input_firstname</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#first-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'first-name') and equals(@name,'firstName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>2dd2d16b-6e2d-482a-98d6-3e264ae2bbc6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>first-name</value>
        <webElementGuid>1fe5fbbf-b162-4037-b893-345d11346970</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>firstName</value>
        <webElementGuid>3211f52e-6b0c-423e-a59b-458b1313faa5</webElementGuid>
    </webElementProperties>
</WebElementEntity>