<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>029dbaac-e8b7-4682-b9dc-17417891bc8d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_tc1_verify_succes_ile_postpaid_plan</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiTableRow-root\\ css-qk26bf"]:nth-child(1) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'TC1-Verify Succes...ile Postpaid Plan')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="TC1-Verify Succes...ile"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TC1-Verify Succes...ile Postpaid Plan</value>
        <webElementGuid>dced2919-fce0-468a-96b2-671df63b5cd0</webElementGuid>
    </webElementProperties>
</WebElementEntity>